[workspace]
resolver = "3"
members = ["crates/gaffer-core", "crates/gafferd", "crates/gaffer"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/jnetto/gaffer"
authors = ["Jose Tiburcio Ribeiro Netto <jnetto@mineiro.dev>"]

[workspace.dependencies]
gaffer-core = { path = "crates/gaffer-core" }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
